/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIWrapper */

#ifndef _Included_JNIWrapper
#define _Included_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIWrapper
 * Method:    sayHello
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JNIWrapper_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
